use_frameworks!

platform :ios, '9.0'

target 'ABCircularProgressView_Example' do
  pod 'ABCircularProgressView', :path => '../'

  target 'ABCircularProgressView_Tests' do
    inherit! :search_paths

    
  end
end
