use_frameworks!

platform :ios, '9.0'

target 'ABFCircularProgressView_Example' do
  pod 'ABFCircularProgressView', :path => '../'

  target 'ABFCircularProgressView_Tests' do
    inherit! :search_paths

    
  end
end
